### ISSUE TITLE
Add the facet slug as a class of the wrapper

### ISSUE THREAD

**Issue by lhall-amphibee** [AmphiBee/wpgb-extended#1]
Current HTML markup of a facet wrapper is :

`<div class="wpgb-facet wpgb-facet-ID" data-facet="ID" data-grid="GRID">`

It would be nice to have 

`<div class="wpgb-facet wpgb-facet-ID FACET_SLUG" data-facet="ID" data-grid="GRID">`

**Comment by ogorzalka** [comment]
so nice !

**Comment by ogorzalka** [comment]
@lhall-amphibee added with https://github.com/AmphiBee/wpgb-extended/commit/09bb10504d8fc866efac8212f4867f7a8a2a7dae
