### ISSUE TITLE
Facet::getBySlug() -- Use caching to avoid performance issues

### ISSUE THREAD

**Issue by lhall-amphibee** [AmphiBee/wpgb-extended#2]
Using a static variable in the class to store previously found slugs could avoid unnecessary DB queries.

**Comment by ogorzalka** [comment]
it would be great indeed !

**Comment by ogorzalka** [comment]
Improved in https://github.com/AmphiBee/wpgb-extended/commit/d4ed9f0468ade4c99caf423ffc1037fe4be9b26a :)
